name: devsecops-demo
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SonarSource/sonarqube-scan-action@v1.0.0
        with: 
        # Additional arguments to the sonar-scanner
          args:#
          projectBaseDir:#
      - uses: snyk/actions@0.3.0
        with:
             # Which Snyk command to run, defaults to test
             command: # optional, default is test
    # Additional arguments to pass to Snyk
             args: # optional
    # Output a snyk.json file with results if running the test command
             json: # optional
             
             - name: Aqua Security Trivy
  # You may pin to the exact commit or the version.
  # uses: aquasecurity/trivy-action@8f4c7160b470bafe4299efdc1c8a1fb495f8325a
  uses: aquasecurity/trivy-action@0.2.1
  with:
    # Scan type to use for scanning vulnerability
    scan-type: # optional, default is image
    # image reference(for backward compatibility)
    image-ref: 
    # reference of tar file to scan
    input: # optional, default is 
    # Scan reference
    scan-ref: # optional, default is .
    # exit code when vulnerabilities were found
    exit-code: # optional, default is 0
    # ignore unfixed vulnerabilities
    ignore-unfixed: # optional, default is false
    # comma-separated list of vulnerability types (os,library)
    vuln-type: # optional, default is os,library
    # severities of vulnerabilities to be displayed
    severity: # optional, default is UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
    # output format (table, json, template)
    format: # optional, default is table
    # use an existing template for rendering output (@/contrib/sarif.tpl, @/contrib/gitlab.tpl, @/contrib/junit.tpl
    template: # optional, default is 
    # writes results to a file with the specified file name
    output: # optional, default is 
    # comma separated list of directories where traversal is skipped
    skip-dirs: # optional, default is 
    # comma separated list of files to be skipped
    skip-files: # optional, default is 
    # specify where the cache is stored
    cache-dir: # optional, default is 
    # timeout (default 5m0s)
    timeout: # optional, default is 
    # filter vulnerabilities with OPA rego language
    ignore-policy: # optional, default is 
    # hide progress output
    hide-progress: # optional, default is true
    # output all packages regardless of vulnerability
    list-all-pkgs: # optional, default is false

    
